#5
request = int(input("Dear customer kindly enter any 3 item in your shopping list.  pres 1 to continue:"))
one = input("input your first item:")
two = input("input your second item:")
three = input("input your third itemr:")
add = (one,two,three)
ti = list(add)
ass = input("KINDLY ADD 3 MORE ITEM  press proceeed to continue:") 
four = input("kindly input the fourth item:")
fifth = input("kindly input the fifth item:")
sixth = input("kindly input the sixth  item:")
ti.append(four)
ti.append(fifth)
ti.append(sixth)
t = tuple(ti)
print("t: " + " | ".join(t))
